<a href="https://colab.research.google.com/github/PhonxayMax/Deep_Learning_with_PyToch_Eli_steven_Luca_Thomas/blob/main/Ch3_1_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#3.2 Tensors: Multidimensional arrays

In [24]:
#a = [1.0, 2.0, 1.0]
a = [1.0, 2.0, 1.0]

##3.2.1 From Python lists to PyTorch tensors

In [25]:
#a[0]
a[0]
a[1]

2.0

In [26]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [27]:
"""
import torch # <1>
a = torch.ones(3) # <2>
a
"""
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

##3.2.2 Constructing our first tensors

In [28]:
a[1]

tensor(1.)

In [29]:
float(a[1])

1.0

In [30]:
a[2] = 2.0
a

tensor([1., 1., 2.])

##3.2.3 The essence of tensors

In [31]:
"""points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0"""
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [32]:
"""points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points"""
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [33]:
"""float(points[0]), float(points[1])"""
float(points[0]), float(points[1])

(4.0, 1.0)

In [34]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [35]:
points.shape

torch.Size([3, 2])

In [36]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [37]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [38]:
points[0, 1]

tensor(1.)

In [39]:
points[0]

tensor([4., 1.])

#3.7 Tensors : Scenic Views of storage

##3.7.1 Indexing into storage

In [95]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [96]:
points_storage = points.storage()
points_storage[0]

4.0

In [99]:
points.storage()[1]

1.0

In [100]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

##3.7.1 Modifying stored values : In-place operations

In [44]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [45]:
second_point.size()

torch.Size([2])

In [46]:
second_point.shape

torch.Size([2])

In [47]:
points.stride()

(2, 1)

In [48]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [49]:
second_point.storage_offset()

2

In [50]:
second_point.stride()

(1,)

In [51]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [52]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [53]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [54]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [55]:
id(points.storage()) == id(points_t.storage())

True

In [56]:
points.stride()

(2, 1)

In [57]:
points_t.stride()

(1, 2)

In [58]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [59]:
transpose_t.shape

torch.Size([5, 4, 3])

In [60]:
some_t.stride()

(20, 5, 1)

In [61]:
transpose_t.stride()

(1, 5, 20)

In [62]:
points.is_contiguous()

True

In [63]:
points_t.is_contiguous()

False

In [64]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [65]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [66]:
points_t.stride()

(1, 2)

In [67]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [68]:
points_t_cont.stride()

(3, 1)

In [69]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

#3.5 Tensor element types

##3.5.1 Specify the numeric type with dtype

##3.5.2 A dtype for every occasion

## 3.5.3 Managing a tensor's dtype attribute

In [86]:
"""double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)"""
double_points = torch.ones(10, 2, dtype=torch.double)
print(double_points)
print(double_points.dtype)
print("---------------------")
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
print(short_points)
print(short_points.dtype)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
torch.float64
---------------------
tensor([[1, 2],
        [3, 4]], dtype=torch.int16)
torch.int16


In [87]:
short_points.dtype

torch.int16

In [88]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [89]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [90]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [91]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

#3.3 Indexing tensors

In [76]:
some_list = list(range(6))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

[1, 3]

In [80]:
print(points)
points[1:]       # <1>
print(points[1:])
points[1:, :]    # <2>
print(points[1:, :])
points[1:, 0]
print(points[1:, 0])    # <3>
points[None]     # <4>

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
tensor([[5., 3.],
        [2., 1.]])
tensor([[5., 3.],
        [2., 1.]])
tensor([5., 2.])


tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [ ]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [ ]:
points = torch.from_numpy(points_np)

In [ ]:
torch.save(points, '../data/p1ch3/ourpoints.t')

In [ ]:
with open('../data/p1ch3/ourpoints.t','wb') as f:
   torch.save(points, f)

In [ ]:
points = torch.load('../data/p1ch3/ourpoints.t')

In [ ]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
   points = torch.load(f)

In [ ]:
import h5py

f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [ ]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [ ]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [ ]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [ ]:
points_gpu = points.to(device='cuda')

In [ ]:
points_gpu = points.to(device='cuda:0')

In [ ]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda')  # <2>

In [ ]:
points_gpu = points_gpu + 4

In [ ]:
points_cpu = points_gpu.to(device='cpu')

In [ ]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

#3.6 The tensor API

In [92]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [93]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [94]:
t1 = torch.ones(3, 3)
t2 = torch.arange(0, 10, 2)
print(t1)
print(t2)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([0, 2, 4, 6, 8])


In [ ]:
a = torch.ones(3, 2)

In [ ]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])